name: Build and Run Gemini Chatbot

on:
  push:
    branches: [ master ]

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Create .env from secret
        run: echo "${{ secrets.ENV_FILE }}" > .env

      - name: Create service account JSON from secret
        run: echo "${{ secrets.SERVICE_ACCOUNT_FILE_CONTENT }}" > service_acc.json

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: docker build -t chatbot-gemini .

      - name: Run chatbot container
        run: docker run --env-file .env chatbot-gemini
